enum NETWORK_EVENT { UPDATE, REMOVE }

enum SHOOTING_CLIENT_EVENT { COUNTDOWN, PICKUP_GUN, MATCH_UPDATE, END_MATCH }

enum STEP_EVENT { BEGIN_STEP, STEP, AFTER_STEP }

enum TRANSITION_MODE { OFF, OPEN, CLOSE }

enum PARTICLE_TYPE { DUST, DIRT, BLOOD, WOOD, ROCK }

enum CHARACTER { GERALDO, RAIMUNDO, SEBASTIAO, SEVERINO }